### ISSUE TITLE
Rubygem? 

### ISSUE THREAD

**Issue by lcpriest** [djudd/human-name-rb#1]
I tried `gem install humanname`, but nothing was available.

**Comment by djudd** [comment]
What platform are you on? 

Looks like I hadn't uploaded a Linux version since switching to Helix, but there's one now: https://rubygems.org/gems/humanname

(I've been fighting with the .travis.yml to try to get these uploaded automatically, but haven't succeeded yet.)

**Comment by lcpriest** [comment]
<img width="605" alt="screenshot 2017-05-30 22 05 34" src="https://cloud.githubusercontent.com/assets/735593/26587152/1e39cb52-4584-11e7-9b7c-a587ecf46c71.png">

I'm on MacOS

**Comment by djudd** [comment]
What version? I'm on 10.12 and it installs. Unfortunately I won't be able to build for an earlier version unless/until I can get Travis artifact builds working.

**Comment by lcpriest** [comment]
I'm on 10.12.4

**Comment by lcpriest** [comment]
Rubygems says there is a runtime dependency of helix-runtime. That is probably why I couldn't see it, my mistake.

**Comment by djudd** [comment]
Hmm, that shouldn't prevent you from `gem install`ing, I think. Ok if I ping you when I have what I think is a correct build uploaded, and you can try again?

**Comment by lcpriest** [comment]
Absolutely! Thanks for your work.

**Comment by cllns** [comment]
Sorry to open this back up, but it looks like `humanname` has been pulled from Rubygems (if it was once there): https://rubygems.org/gems/humanname

I was able to install it using `specific_install` extension to the `gem` command.
